# SPDX-FileCopyrightText: 2025 Upbound Inc. <https://upbound.io>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../crds

patches:
- path: webhook.yaml
  target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition

transformers:
  - splitter.yaml
